name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV

      - name: Deploy
        run: |
          # команды для деплоя здесь
